server:
  port: 8080

spring:
  datasource:
    url: # DB URL
    username: # userName
    password: # password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  security:
    debug: true

logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.resource.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    root: DEBUG

jwt:
  secret:
    key: # JWT Salt Key