server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/mine"
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000  #??? ??
  security:
    debug: true

logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.resource.transaction: DEBUG
    org.hibernate.SQL: DEBUG  # jpa hibernate? ???? sql? ??? ??? ????? ??
    org.hibernate.type: TRACE # ???? ??? ??

jwt:
  secret:
    key: 4B1F395D6E82793CF54863EA8B6EC9324448BC1397E3DC754B45E4DF23